version : "3.9"
services :
    flaskapp :
        build: .
        image: titanic-flask:latest
        ports:
          - "5000:5000"
        environment:
          FLASK_ENV: development
        depends_on:
          - postgres
    postgres:
        image: "postgres:latest"
        environment:
          - POSTGRES_USER=POSTGRES_USER
          - POSTGRES_PASSWORD=POSTGRES_PASSWORD
          - POSTGRES_DB=POSTGRES_DB